version: '3.8'

services:
  # =========================
  # HDFS - Hadoop
  # =========================
  namenode:
#    platform: linux/amd64
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=velib-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - velib-net

  datanode1:
#    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    ports:
      - "9864:9864"
    environment:
      - CLUSTER_NAME=velib-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - velib-net

  datanode2:
#    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    ports:
      - "9865:9864"
    environment:
      - CLUSTER_NAME=velib-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - velib-net

  datanode3:
#    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    restart: always
    ports:
      - "9866:9864"
    environment:
      - CLUSTER_NAME=velib-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - velib-net

  # =========================
  # SPARK
  # =========================
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master --port 7077 --webui-port 8080
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - velib-net
    volumes:
      - ./spark:/opt/spark-apps

  spark-worker1:
    image: apache/spark:3.5.0
    container_name: spark-worker1
    environment:
      - SPARK_MODE=worker
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - velib-net

  # =========================
  # MONGODB
  # =========================
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=velibdb
    networks:
      - velib-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================
  # BACKEND API
  # =========================
  backend:
    build: ./back
    container_name: velib-backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017/velib_kpi_batch
    networks:
      - velib-net
    volumes:
      - ./back:/app
      - /app/node_modules

  # =========================
  # INGESTION - Récupération API + HDFS
  # =========================
  velib-ingestion:
    build: ./ingestion
    container_name: velib-ingestion
    depends_on:
      - namenode
      - mongodb
    networks:
      - velib-net
    environment:
      - HDFS_URL=http://namenode:9870
      - FETCH_INTERVAL=60
      - MONGO_URI=mongodb://mongodb:27017/velibdb
      - USE_MONGODB=true

networks:
  velib-net:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  mongo_data:
