services:
  # =========================
  # HDFS - Hadoop
  # =========================
  namenode:
    #    platform: linux/amd64
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=velib-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - velib-net

  datanode1:
    #    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    ports:
      - "9864:9864"
    environment:
      - CLUSTER_NAME=velib-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - velib-net

  datanode2:
    #    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    ports:
      - "9865:9864"
    environment:
      - CLUSTER_NAME=velib-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - velib-net

  datanode3:
    #    platform: linux/amd64
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    restart: always
    ports:
      - "9866:9864"
    environment:
      - CLUSTER_NAME=velib-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - velib-net



  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    volumes:
      - ./spark:/opt/spark-apps
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - velib-net

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - velib-net

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - velib-net

  spark-worker-3:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - velib-net

  # =========================
  # MONGODB
  # =========================
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=velibdb
    networks:
      - velib-net

# =========================
  # BACKEND API
  # =========================
  backend:
    build: ./back
    container_name: velib-backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017/velib_kpi_batch
    networks:
      - velib-net
    volumes:
      - ./back:/app
      - /app/node_modules

  velib-ingestion:
    build: ./ingestion
    container_name: velib-ingestion
    depends_on:
      - namenode
    networks:
      - velib-net
    environment:
      - HDFS_URL=http://namenode:9870
      - FETCH_INTERVAL=60

  # =========================
  # FRONTEND
  # =========================
  frontend:
    build: ./front
    container_name: velib-frontend
    restart: always
    ports:
      - "5174:5173"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000/api
    networks:
      - velib-net
    volumes:
      - ./front:/app
      - /app/node_modules

networks:
  velib-net:

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  mongo_data: